---
AWSTemplateFormatVersion" : 2010-09-09
 Description: 
    This template launches ec2 instance
Resources: 
    MyEc2:
        Type: AWS::EC2::Instance
        Properties: 
            ImageId: ami-0b5eea76982371e91
            InstanceType: t2.micro
            KeyName: LinuxPlus 
            SecurityGroups:
              - launch-wizard-1
            Tags:
               - Key: Name
                Value: First-CF-Stack-Instance
            